*** Settings ***
Documentation      Locators for all android logic


*** Variables ***
${GET_STARTED_BUTTON}                       //android.view.View[@content-desc="Get started"]
${I_ACCEPT_BUTTON}                          //android.view.View[@content-desc="I accept"]
${NEXT_BUTTON}                              //android.view.View[@content-desc="Next"]
${SIGNIN_BUTTON}                            //android.view.View[@content-desc="Sign in"]
${NEXT_BUTTON_ON_SELECT_COUNTRY_WIDGET}     //android.widget.Button[@text="Next"]
${EMAIL_ADDRESS_FIELD}                      //android.widget.EditText[@hint="Email address"]
${PASSWORD_FIELD}                           //android.widget.EditText[@hint="Password"]
${CONTINUE_BUTTON}                          //android.widget.Button[@text="Continue"]
${YES_CONTINUE_BUTTON}                      //android.view.View[@content-desc="Yes, continue"]
${START_SETUP_BUTTON}                       //android.view.View[@content-desc="Start setup"]
${ENTER_MANUALLY_PASSPHRASE_BUTTON}         //android.view.View[@content-desc="Enter manually"]
${PASSPHRASE_FIELD}                         //android.widget.EditText[@hint='super secret secure undefeatable passphrase']
${YES_TURN_THEM_ON}                         //android.view.View[@content-desc="Yes, turn them on"]
${PERMISSION_ALLOW_BUTTON}                  com.android.permissioncontroller:id/permission_allow_button
${SKIP_BUTTON}                              //android.view.View[@content-desc="Skip"]
${DONE_BUTTON}                             //android.view.View[@content-desc="Done"]
${SECURITY_BUTTON}                         //android.view.View[@content-desc="SECURITY"]






