*** Settings ***
Documentation      Locators for all android logic


*** Variables ***
${GET_STARTED_BUTTON}                       //android.view.View[@content-desc="Get started"]
${I_ACCEPT_BUTTON}                          //android.view.View[@content-desc="I accept"]
${NEXT_BUTTON}                              //android.view.View[@content-desc="Next"]
${SIGNIN_BUTTON}                            //android.view.View[@content-desc="Sign in"]
${NEXT_BUTTON_ON_SELECT_COUNTRY_WIDGET}     //android.widget.Button[@text="Next"]
${EMAIL_ADDRESS_FIELD}                      //android.webkit.WebView[@text="Sign in | Philips Hue"]/android.view.View[2]/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View[1]/android.widget.EditText
${PASSWORD_FIELD}                           //android.webkit.WebView[@text="Sign in | Philips Hue"]/android.view.View[2]/android.view.View/android.view.View/android.view.View/android.view.View[2]/android.view.View[2]/android.widget.EditText
${CONTINUE_BUTTON}                          //android.widget.Button[@text="Continue"]
${YES_CONTINUE_BUTTON}                      //android.view.View[@content-desc="Yes, continue"]
${START_SETUP_BUTTON}                       //android.view.View[@content-desc="Start setup"]
${ENTER_MANUALLY_PASSPHRASE_BUTTON}         //android.view.View[@content-desc="Enter manually"]
${PASSPHRASE_FIELD}                         //android.widget.FrameLayout[@resource-id="android:id/content"]/android.widget.FrameLayout/android.view.View/android.view.View/android.view.View/android.view.View[3]







