*** Settings ***
Documentation      Locators for all vertical screens


*** Variables ***
${VERTICAL_PICTURE_MAIN_SCREEN}           ru.afisha.android:id/feedRv
${STORIES}                                ru.afisha.android:id/storiesRv
${FAVORITES}                              ru.afisha.android:id/itemTileFavoriteBtn
${DAILY_SCREEN}                           ru.afisha.android:id/itemHeaderTitleTv
${some}                                   ru.afisha.android:id/itemHeaderTitleTv

