*** Settings ***
Documentation      Locators for all vertical screens


*** Variables ***
${VERTICAL_PICTURE_MAIN_SCREEN}           ru.afisha.android:id/feedRv
${STORIES}                                ru.afisha.android:id/storiesRv
${FAVORITES}                              ru.afisha.android:id/itemTileFavoriteBtn
${DAILY_SCREEN}                           ru.afisha.android:id/itemHeaderTitleTv
${FIRST_VIEW_STORIES}                     ru.afisha.android:id/itemStoryImage
${PICTURE_FIRST_VIEW_STORIES}             ru.afisha.android:id/fragStoriesIv
${BTN_VIEW_STORIES}                       ru.afisha.android:id/fragStoriesTitleWidgetBtn
${CLOSE_VIEW_STORIES}                     ru.afisha.android:id/fragStoriesCloseIv
${MARK_VIEW_STORIE_ON_SCREEN}             ru.afisha.android:id/itemStoryViewedMark
${ITEM_STORY_TITLE}                       ru.afisha.android:id/itemStoryTitle


